<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tpl.php</string>
	</array>
	<key>name</key>
	<string>BlackBox Templates</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.php</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant</string>
				</dict>
			</dict>
			<key>match</key>
			<string>{(foreach|while|if|elseif|for|switch|case|include|section|yield|extend)\((.+)\)}</string>
			<key>name</key>
			<string>variable.blackbox</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant</string>
				</dict>
			</dict>
			<key>match</key>
			<string>{(else|default|break|continue)}</string>
			<key>name</key>
			<string>variable.blackbox</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant.blackbox</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.blackbox</string>
				</dict>
			</dict>
			<key>match</key>
			<string>{(define)\((.+), (.+)\)}</string>
			<key>name</key>
			<string>variable.blackbox</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant.blackbox</string>
				</dict>
			</dict>
			<key>match</key>
			<string>{/(foreach|while|if|for|switch|case|default|section)}</string>
			<key>name</key>
			<string>variable.blackbox</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.constant.blackbox</string>
				</dict>
			</dict>
			<key>match</key>
			<string>{{(.+?)}}</string>
			<key>name</key>
			<string>variable.blackbox</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.blackbox</string>
</dict>
</plist>
